language: scala
scala:
  - 2.12.7
jdk:
  - oraclejdk8
  - openjdk11
env:
  matrix:
    - SCRIPT=scripts/test-sbt
    - SCRIPT=scripts/test-gradle
    - SCRIPT=scripts/validate-gatling
script:
  - $SCRIPT
cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.gradle/caches"
before_cache:
  - rm -rf $HOME/.ivy2/cache/com.typesafe.play/*
  - rm -rf $HOME/.ivy2/cache/scala_*/sbt_*/com.typesafe.play/*
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print0 | xargs -n10 -0 rm

# Exclude some combinations from build matrix. See:
# https://docs.travis-ci.com/user/customizing-the-build/#Build-Matrix
matrix:
  fast_finish: true
  allow_failures:
    # Current release of Gradle still does not supports Play 2.7.x releases
    # As soon as there is a release of Gradle that fixes that, we can then
    # remove this allowed failure.
    - env: SCRIPT=scripts/test-gradle
    # Java 11 is still not fully supported. It is good that we are already
    # testing our sample applications to better discover possible problems
    # but we can allow failures here too.
    - jdk: openjdk11
