language: scala
dist: trusty
sudo: true
group: beta
scala:
- 2.11.11
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot/"
before_cache:
- rm -rf $HOME/.ivy2/cache/com.typesafe.play/*
- rm -rf $HOME/.ivy2/cache/scala_*/sbt_*/com.typesafe.play/*
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -print0 | xargs -n10 -0 rm
- find $HOME/.sbt -name "*.lock" -delete
notifications:
  email:
    recipients:
      - searchprodmail@gmail.com
    on_success: never # default: change
    on_failure: always # default: always